**Vectors and Matrices in Python (NumPy Hands On)**

In this lesson we connect the Linear Algebra ideas to actual Python code.
We will use NumPy to create vectors and matrices and do basic operations
that appear inside Machine Learning models.

In [1]:
%pip install -q numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True) # cleaner printing (no scientific notation)


**1. Scalar, Vector, Matrix & Tensor in NumPy**

In [5]:
# scalar - single number
scalar = 5.0
print(scalar)
print("Type of Scalar:", type(scalar))

print("-"*40)

# vector - 1D data
vector = np.array(
    [3, 7, 2]
)
print("Vector:")
print(vector)
print("Shape of vector:", vector.shape)

print("-"*40)

# matrix - 2D data
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print("Matrix:")
print(matrix)
print("Shape of matrix:", matrix.shape)

print("-"*40)

# Tensor - 3D data
tensor = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [11, 12, 13],
            [14, 15, 16]
        ]
    ]
)


print("Tensor:")
print(tensor)
print("Shape of tensor:", tensor.shape)

5.0
Type of Scalar: <class 'float'>
----------------------------------------
Vector:
[3 7 2]
Shape of vector: (3,)
----------------------------------------
Matrix:
[[1 2 3]
 [4 5 6]]
Shape of matrix: (2, 3)
----------------------------------------
Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
Shape of tensor: (2, 2, 3)


**2. Creating vectors and matrices for ML style data**

In [3]:
# Imagine we have 3 samples and 2 features
# Feature 1: hours studied
# Feature 2: number of practice questions
# target: pass (1)/ fail (0)

X = np.array(
    [
        [2, 30],  # sample 1
        [5, 80],  # sample 2
        [1, 20]   # sample 3
    ]
)

y = np.array([0, 1, 0]) 

print("Input Data matrix X:\n", X)
print("X shape:", X.shape)  # (n_samples, n_features)

print("Output Vector y:\n", y)
print("y shape:", y.shape)  # (n_samples,)


# A single sample as a vector
x1 = X[0]  # first row
print("\nFirst sample as a vector:", x1)
print("x1 shape:", x1.shape)   # (2,)

Input Data matrix X:
 [[ 2 30]
 [ 5 80]
 [ 1 20]]
X shape: (3, 2)
Output Vector y:
 [0 1 0]
y shape: (3,)

First sample as a vector: [ 2 30]
x1 shape: (2,)


**3. Basic operations: addition, scalar multiplication, transpose**

In [4]:
# Two vectors with same length
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("v1:", v1)
print("v2:", v2)

# vector addition
v_add = v1 + v2
print("\nVector addition v1 + v2:", v_add)

# scalar multiplication
v1_scaled = 2 * v1
print("Scalar multiplication 2 * v1:", v1_scaled)


# Matrix example
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

print("\nMatrix A:\n", A)
print("Matrix B:\n", B)

# Matrix addition
A_add_B = A + B
print("\nMatrix addition A + B:\n", A_add_B)

# Scalar multiplication
A_scaled = 0.5 * A
print("Scalar multiplication 0.5 * A:\n", A_scaled)

# transpose
A_T = A.
print("\nTranspose of A:\n", A_T)
print("A shape:", A.shape, "| A.T shape:", A_T.shape)

v1: [1 2 3]
v2: [4 5 6]

Vector addition v1 + v2: [5 7 9]
Scalar multiplication 2 * v1: [2 4 6]

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[10 20]
 [30 40]]

Matrix addition A + B:
 [[11 22]
 [33 44]]
Scalar multiplication 0.5 * A:
 [[0.5 1. ]
 [1.5 2. ]]

Transpose of A:
 [[1 3]
 [2 4]]
A shape: (2, 2) | A.T shape: (2, 2)
