In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True)

**Dot Product**

In [4]:
v1 = np.array([1, 3])
v2 = np.array([4, 2])

print('v1:', v1)
print('v2:', v2)

v1: [1 3]
v2: [4 2]


In [6]:
dot = np.dot(v1, v2)
print("Dot Product v1.v2:", dot)

Dot Product v1.v2: 10


**Euclidean Distance**

In [7]:
diff = v1 - v2
print("Difference v1 - v2:", diff)

Difference v1 - v2: [-3  1]


In [8]:
distance = np.linalg.norm(diff)
print("Euclidean distance between v1 and v2:", distance)

Euclidean distance between v1 and v2: 3.1622776601683795


**Matrix Multiplication and Linear Model**

In [9]:
X = np.array([
    [1.0, 30.0],
    [2.0, 50.0],
    [3.0, 70.0]
])

print("X:\n", X)
print("X shape:", X.shape)

X:
 [[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]
X shape: (3, 2)


In [10]:
w = np.array([
    [0.5],
    [0.1]
])

print("\nw:\n", w)
print("w shape:", w.shape)


w:
 [[0.5]
 [0.1]]
w shape: (2, 1)


In [11]:
Xw = X @ w
print("\nXw:\n", Xw)
print("Xw shape:", Xw.shape)


Xw:
 [[3.5]
 [6. ]
 [8.5]]
Xw shape: (3, 1)


**y = Xw + b**

In [12]:
b = 2.0
print("\nBias b:", b)


Bias b: 2.0


In [13]:
y = Xw + b
print("\nPredictions y = Xw + b:\n", y)
print("y shape:", y.shape)


Predictions y = Xw + b:
 [[ 5.5]
 [ 8. ]
 [10.5]]
y shape: (3, 1)


In [14]:
print(X)

[[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]


In [15]:
print(w)

[[0.5]
 [0.1]]


In [16]:
print(b)

2.0


In [22]:
print(y)

[[ 5.5]
 [ 8. ]
 [10.5]]


**Connecting this to a sample dataset**

In [17]:
data = np.array([
    [85, 26.6, 31, 0],
    [183, 23.3, 32, 1],
    [89, 28.1, 21, 0],
    [137, 43.1, 33, 1],
])

print("Full data matrix:\n", data)
print("Data shape:", data.shape)

Full data matrix:
 [[ 85.   26.6  31.    0. ]
 [183.   23.3  32.    1. ]
 [ 89.   28.1  21.    0. ]
 [137.   43.1  33.    1. ]]
Data shape: (4, 4)


In [18]:
X_features = data[:, :-1]
y_target = data[:, -1]

print("\nFeature matrix X:\n", X_features)
print("X shape:", X_features.shape)

print("\nTarget vector y:\n", y_target)
print("y shape:", y_target.shape)


Feature matrix X:
 [[ 85.   26.6  31. ]
 [183.   23.3  32. ]
 [ 89.   28.1  21. ]
 [137.   43.1  33. ]]
X shape: (4, 3)

Target vector y:
 [0. 1. 0. 1.]
y shape: (4,)
